= Security and Compliance in an Image Mode world.

Building and deploying using Image Mode has some built-in benefits from a security and compliance perspective.  
First, systems deployed with Image Mode are more likely to be built to your desired specifications, and second it is much easier to make sure that they stay that way.  
In the next few modules we'll walk through how to add security and compliance into your build, and also how to apply that policy using automation.  
We will also touch a bit on drift and getting your systems back into compliance after an event.

[NOTE] 
====
Because we will be making significant changes to our system, we are going to start fresh.  First we will build an updated bootc image, and then we will build a new guest vm just like we did at the beginning of the lab.
====

== Adding security controls to your image: FAPolicyd
==== _Click on the tab labeled "Build host"_ 
One of the common services the security team uses to meet compliance and security mandates is FAPolicyD.
The File Access Policy Daemon is a service that implements application allow-listing.  So let's see what it looks like to simply add it to our `Containerfile`.  

NOTE: We will be adding these changes after the `systemctl mask` line at the end of the existing file

[source,bash,role="execute",subs=attributes+]
----
cd ~/bootc-base
nano Containerfile
----


FAPolicyD is one of the standard tools the security team asked for, including the audit subsystem and SELinux troubleshooting. We'll also install the packages for the SCAP policy tools now since we know that's coming.

[source,dockerfile,role="execute",subs=attributes+]
----
# Security and Hardening 
RUN dnf -y install audit fapolicyd openscap-utils scap-security-guide setroubleshoot-server

RUN systemctl enable fapolicyd
----

Notice the only thing that needs to be defined to get FAPolicyD running at boot is a standard `systemctl` call.
Since we are targeting full RHEL systems and not containers, systemd is always running and available post-install so there's no need for any additional `init` environments or `ENTRYPOINT` definitions.

Save the changes, and exit your editor.
 

= Building policy into a bootc image

Now, we could add all of the various packages and configuration changes directly to our Containerfile and achieve the security team's goals.  But, much like a package mode RHEL host, we can leverage automation to get the bulk of the work done using SCAP policies. 

== Tailoring SCAP for compliance
The security team uses the CIS Level 1 policy with some deviations for all public facing webservers.
To setup our openscap policy, we will first make a change to the policy using `autotailor`. 
You will likely need to tailor any compliance policy to your organization's needs as these aren't one size fits all.
In our example we are simply turning root logins back on so as not to break the lab environment. 

To do this, we will tailor our policy right on our build host.
Tailoring files are a common format and as long as they are built against the right policy, they can be created on any host.
The `autotailor` command comes from the `openscap-utils` package, and requires that the `scap-security-guide` is also installed.

[source,bash,role="execute",subs=attributes+]
----
cd ~/bootc-base
autotailor --unselect xccdf_org.ssgproject.content_rule_sshd_disable_root_login \
  --new-profile-id cis_server_l1_customized \
  --output cis_server_l1_customized.xml \
  /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml cis_server_l1
----
<.> The rule to deselect
<.> The new policy name to use
<.> The name of the policy file to write
<.> The original policy to tailor

Then we'll modify our Containerfile, removing the line where we enable FAPolicyd, and replacing it with an oscap policy block. Notice that the cis_server_l1_customized.xml file that we generated with autotailor is used here. This file will contain your modified policy, and can be re-used on other build that you would like to apply the same custom policy to. 

We'll use the new `oscap-im` tool to scan and remediate the image at build time.
This tool is also part of the `openscap-utils` package and is specially designed for operating inside a containerized build.

Remember, labels are for humans, so adding something about the compliance configuration that can be read from the registry or locally without starting or examining a running host is helpful.

Open up the Containerfile, and then add the following after the `systemctl enable` line.

[source,bash,role="execute",subs=attributes+]
----
nano Containerfile
----

[source,dockerfile,role="execute",subs=attributes+]
----
LABEL profile="CIS Server Level 1 base image"
ENV profileID=cis_server_l1_customized <.>

COPY $profileID.xml /tmp/$profileID.xml
RUN oscap-im --profile $profileID --tailoring-file /tmp/$profileID.xml /usr/share/xml/scap/ssg/content/ssg-rhel10-ds.xml <.>
----
<.> An environment variable to define the policy to apply
<.> The new `oscap-im` command using our tailored policy

With that in place, we can build our bootc image again. 

[source,bash,role="execute",subs=attributes+]
----
podman build --file Containerfile --tag registry-{guid}.{domain}/base
----
As the bootc image builds, you will see output similar to this as the openscap profile is getting applied to the image. 
....
xccdf_org.ssgproject.content_rule_package_aide_installed:pass
xccdf_org.ssgproject.content_rule_aide_build_database:fail
xccdf_org.ssgproject.content_rule_aide_check_audit_tools:fail
xccdf_org.ssgproject.content_rule_aide_periodic_cron_checking:fail
xccdf_org.ssgproject.content_rule_configure_crypto_policy:pass
xccdf_org.ssgproject.content_rule_configure_ssh_crypto_policy:pass
xccdf_org.ssgproject.content_rule_partition_for_dev_shm:notapplicable
xccdf_org.ssgproject.content_rule_partition_for_tmp:notapplicable
xccdf_org.ssgproject.content_rule_dconf_db_up_to_date:notapplicable
....

After it completes, push the new image.

[source,bash,role="execute",subs=attributes+]
----
podman push registry-{guid}.{domain}/base
----

Since we've added a few labels now, let's use `skopeo` to pull them from the latest image and use `jq` to pretty up the output.
[source,bash,role="execute",subs=attributes+]
----
skopeo inspect --format '{{json .Labels }}' docker://registry-{guid}.{domain}/base | jq
----
There's quite a few labels applied by default that describe RHEL version, architecture, creation dates, release info, and if this is in fact a bootc image. There's also our CIS profile and our company name as the vendor.

Now that we have our new image built, we can update our automatically dployed bootc virtual machine using the newly hardened image.

==== _Click on the tab labeled "Bootc VM"_

On our bootc host, we'll simply apply the bootc updates. 

[source,bash,role="execute",subs=attributes+]
----
sudo bootc update --apply
----


Let's test the security controls in the next module!
